### ISSUE TITLE
Application switcher does not work

### ISSUE THREAD

**Issue by akabhirav** [Simmesimme/Gnome-Pie#119]
The window list and device list, although display everything correctly don't switch to applications when clicked. Is this a bug or it's just not implemented yet.

**Comment by Simmesimme** [comment]
Hey thanks for the report! It works for me... What version of Gnome-Pie and which linux distro are you using? And which window manager?

**Comment by akabhirav** [comment]
I am using gnome-pie 0.5.6 on Ubuntu 15.04 with Linux 3.19.0-28 and Unity window manager

**Comment by Simmesimme** [comment]
I think the problem you are describing was fixed in v0.6.2. The current version of Gnome-Pie is 0.6.5. So your problem should be fixed by installing the most recent version!

There are installation instructions using my PPA on the homepage of Gnome-Pie: http://simmesimme.github.io/gnome-pie.html

Hope this helps! If not, please re-open this issue!
