### ISSUE TITLE
Color extractor for adaptative text color [FEATURE REQUEST]

### ISSUE THREAD

**Issue by WhippetsAintDogs** [Simmesimme/Gnome-Pie#126]
I know that we can use the colorize="true" option in themes in order to get the color of the pointed icon and apply it to a given text. But, it would be useful to extract the background color instead in order to get a good contrast between the background and the text. (like a contrast_color="true", to get an adaptative color in the range of white-gray-black.) You already have a similar implementation with your Color Splash! project, so I'm just throwing up the idea :) .

Marc-Antoine

**Comment by Simmesimme** [comment]
Hi Marc-Antoine!

Can you give an example of what you are trying to achieve? Since the extracted color is always quite bright and saturated ([this line](https://github.com/Simmesimme/Gnome-Pie/blob/master/src/utilities/color.vala#L141) guarantees a brightness value of one; saturation is always greater than 0.65), dark backgrounds will always work.

BTW, my website uses pretty much the [same code](https://github.com/Simmesimme/Simmesimme.github.io/blob/master/_color_extractor/color.vala#L88) for Color Splash.

**Comment by washburn94** [comment]
![imag01069](https://cloud.githubusercontent.com/assets/9271409/10430000/98a36a64-70ca-11e5-8c1e-bf182f76f114.jpg)
![imag0104](https://cloud.githubusercontent.com/assets/9271409/10430001/98a7fa34-70ca-11e5-94ef-2ac96e1171d3.jpg)
![imag0105](https://cloud.githubusercontent.com/assets/9271409/10430002/98a7ee0e-70ca-11e5-8a10-bbfd3431e4b4.jpg)

For the text in the center, I just don't wan't to use colorize="true" since it overlaps the ring. If the text could understand on what background color it is printed and colorize itself in a white-grey-black color range adaptatively in order to get a good contrast between the two, it'll be awesome.

**Comment by Simmesimme** [comment]
This seems quite difficult because the background you are referring to is not part of Gnome-Pie. What should happen if you open a Pie in front of some high contrast image, such as a checker board? Should every letter adapt its color on its own? What should happen if you open a Pie in front of something which moves, such as a video?

Maybe it would be a better solution to support outlines and drop shadows for text?

BTW, you can make screenshots of gnome-pie with `gnome-screenshot --delay 5` :-)
