### ISSUE TITLE
long press dosent work in 0.6.9

### ISSUE THREAD

**Issue by xbyte1024** [Simmesimme/Gnome-Pie#132]
I run mint linux 17 Qiana with mint.
After the last update a few days ago, gnome-pie updated to 0.6.9
Since then, long press option doesn’t work. No matter if it is selected or not the pie appears instantaneously.
This is serious problem to me because I use forward and back with long press as main functions, so I cant navigate easily now.

**Comment by Simmesimme** [comment]
Hi there! 
Too bad, I thought that I had tested everything! But it should be fixed in develop now. If you want to, you may compile it from source (actually quite easy: http://simmesimme.github.io/gnome-pie.html#toc4) and report whether everything is working as supposed!
I will wait some days (because there may be more bugs around) and then I'll update the PPA!
Thanks for reporting the issue!

**Comment by xbyte1024** [comment]
Thanks
I installed from code, but I guess I did something wrong. I have the same version installed. I will wait for the repository update, or I will experiment again later. I hope the repository install will override the from source one.

**Comment by Simmesimme** [comment]
Did you perform

`git checkout develop` 

after cloning the repository? The fix is not yet in the master branch!

**Comment by xbyte1024** [comment]
I did it again and now it works!
I think I understood my mistake. Because I didn't see any downloading when changed branch, I re-cloned git, and I worked with the new directory! I thought one of the times I did it this why also, but it seems I didn't.
I should learn at least git basics! Thanks a lot.

**Comment by Simmesimme** [comment]
FYI: v0.7.0 containing this fix has been released: http://simmesimme.github.io/news/2016/09/20/gnome-pie-070

Thanks again for your report!

**Comment by xbyte1024** [comment]
Thanks for the immediate solution.
