### ISSUE TITLE
Performance 

### ISSUE THREAD

**Issue by PhoenixGR** [Simmesimme/Gnome-Pie#151]
Before i get to the point i want to say that just yesterday i read an article on omgubuntu site i gave it a shot and i m amazed! i removed the cairo dock and now i only use gnome-pie good job !  
So while its really stable and its working really good it uses to much process power to work while is open the xorg task uses 15-20% of cpu. Is it a driver problem ? I use nvidia drivers on ubuntu 17.04 my laptop has an i5-2410M and 8GB RAM ddr3  i use the CPU's GPU  and not the dedicated GPU but it should not be an issue.

**Comment by Simmesimme** [comment]
I am glad you like it!

Well, first of all Gnome-Pie runs entirely on your CPU, the GPU is not involved at all. On my laptop Intel® Core™ i7-7700HQ with 8 cores I can hit 5% of one core which in my opinion is totally fine given the fact that Gnome-Pie is redrawn 60 times a second.

Of course it could be optimized - only redraw when something changed color or moved - but since you will usually open Gnome-Pie for some seconds and then it will be closed again I would not consider this to be an issue. It's nothing you have running constantly in the background.

**Comment by PhoenixGR** [comment]
I see! Well yes indeed its just fir few seconds so it is not a major problem. And yes the 60fps is  a must t keep it smooth as it is now.  However is it possible to make the it be rendered from the GPU ? I dont know anything about the Vala so i dont know if there is API for gpu rendering. It might not be an issue but it will be more sufficient. I hope i can find the time to look into the code and see whats what. I m going to keep this launcher and it has much potential.
