### ISSUE TITLE
Too many applications in a category freezing gnomepie

### ISSUE THREAD

**Issue by ryanvade** [Simmesimme/Gnome-Pie#80]
I found gnomepie after reading an article by noobslab.   Really nice but when I open the games category (or any other category with a lot of applicatioins) gnomepie freezes, high cpu usage and graphics lockup.  I am on Arch Linux with gnome 3.14.2

**Comment by Simmesimme** [comment]
Thank you for the report.

Gnome-Pie is not designed to display many items. If there are, let's says, more than 15 items per pie it's hardly usable anymore. In such a case you might consider designing an alternative menu structure with less items per category. (for example create sub-categories for each type of game you have)

Nevertheless Gnome-Pie should not crash, so that is obviously a bug. How many apps do you have in this category?

**Comment by ryanvade** [comment]
70+ I think.  Maybe a feature request but how about multiple rings?

**Comment by Simmesimme** [comment]
This has been fixed in 7912369d1c684c369d770f198cbedb18216224c4. There is a setting for maximum slices per pie in the settings menu. If there are more slices, you can scroll through them with your mouse wheel!
